module Slack.Internal.Types
  ( ChannelId(..)
  , Channel(..)
  , MessageId(..)
  , ChatMessage(..)
  , SlackArchive(..)
  , mkSlackArchive
  , getUser
  , getChannel
  , countNumberOfChatMessages
  , mergeArchive
  , UserId(..)
  , User(..)
  ) where

import Slack.Internal.Types.Channel
import Slack.Internal.Types.ChatMessage
import Slack.Internal.Types.SlackArchive
import Slack.Internal.Types.User